version: '3'
services:
  server:
    build: .
    expose: [8080]
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.web.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.usersfile=/traefik/htpasswd'
    environment:
      DATAFILE_PATH: '/eisen/data.json'
    volumes:
      - /opt/eisen:/eisen

  proxy:
    image: traefik:v3.1
    command:
      - '--log.level=DEBUG'
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=demo@${DOMAIN}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/letsencrypt:/letsencrypt
      - /opt/traefik/htpasswd:/traefik/htpasswd:ro
